services:
    mysql-auth:
        build:
            context: ./mysql/auth
            dockerfile: ./Dockerfile
        ports:
            - "3307:3306"
        networks:
            - cab-booking
        volumes:
            - ./mysql/auth/sql-scripts:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
    mysql-booking:
        build:
            context: ./mysql/booking
            dockerfile: ./Dockerfile
        ports:
            - "3308:3306"
        networks:
            - cab-booking
        volumes:
            - ./mysql/booking/sql-scripts:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
    cab-frontend:
        build: 
            context: ./frontend
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
        networks:
            - cab-booking
    auth-service:
        build: 
            context: ./backend/auth-service
            dockerfile: ./Dockerfile
        ports:
            - "8081:8080"
        networks:
            - cab-booking
        depends_on:
            mysql-auth:
                condition: service_healthy
    booking-service:
        build: 
            context: ./backend/booking-service
            dockerfile: ./Dockerfile
        ports:
            - "8082:8080"
        networks:
            - cab-booking
        depends_on:
            mysql-booking:
                condition: service_healthy

networks:
    cab-booking: