CREATE TABLE user_details (
	id INT NOT NULL AUTO_INCREMENT, 
	username VARCHAR(255) NOT NULL UNIQUE, 
	password VARCHAR(255) NOT NULL DEFAULT '', 
	roles VARCHAR(255) NOT NULL DEFAULT '', 
	enabled BOOLEAN NOT NULL DEFAULT 1,
	PRIMARY KEY (id)
);